version: '3.1'
services:
  elastic:
    image: elasticsearch:8.8.0
    container_name: elastic
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
    env_file:
      - .env
    expose:
      -  9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - elastic:/usr/share/elasticsearch/data

  redis:
    image: redis
    ports:
      - "6379:6379"

  etl:
    build: postgres_to_es/
    container_name: etl
    depends_on:
      - elastic
      - redis
    env_file:
      - .env


volumes:
  elastic:
    driver: local